# encoding: UTF-8
# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

assemblies = Assembly.create([
  {title: 'Alster-Nyedsbygdens församling'},
  {title: 'Arvika västra församling'},
  {title: 'Arvika östra församling'},
  {title: 'Blomskogs församling'},
  {title: 'Boda församling'},
  {title: 'Bolstads församling'},
  {title: 'Bro församling'},
  {title: 'Brunskogs församling'},
  {title: 'Brålanda församling'},
  {title: 'Bäcke församling'},
  {title: 'Dals-Eds församling'},
  {title: 'Degerfors-Nysunds församling'},
  {title: 'Ed-Borgviks församling'},
  {title: 'Eda församling'},
  {title: 'Ekshärads församling'},
  {title: 'Filipstads församling'},
  {title: 'Forshaga församling'},
  {title: 'Frykeruds församling'},
  {title: 'Fryksände församling'},
  {title: 'Frändefors församling'},
  {title: 'Färgelanda församling'},
  {title: 'Gestads församling'},
  {title: 'Gillberga församling'},
  {title: 'Glava församling'},
  {title: 'Grava församling'},
  {title: 'Grums församling'},
  {title: 'Gräsmarks församling'},
  {title: 'Gunnarskogs församling'},
  {title: 'Hagfors-Gustav Adolfs församling'},
  {title: 'Hammarö församling'},
  {title: 'Holmedal-Karlanda församling'},
  {title: 'Holms församling'},
  {title: 'Högsäters församling'},
  {title: 'INTERNATIONELLT ARBETE'},
  {title: 'Järbo-Råggärd församling'},
  {title: 'Järnskog-Skillingmarks församling'},
  {title: 'Karlskoga församling'},
  {title: 'Karlstads domkyrkoförsamling'},
  {title: 'Karlstads stift'},
  {title: 'Kila församling'},
  {title: 'Kristinehamns församling'},
  {title: 'Kville Fjällbacka Svenneby och Bottna'},
  {title: 'Kville Fjällbacka Svenneby och Bottna församlingar'},
  {title: 'Köla församling'},
  {title: 'Laxarby församling'},
  {title: 'Lekvattnets församling'},
  {title: 'Lysviks församling'},
  {title: 'Långseruds församling'},
  {title: 'Mangskogs församling'},
  {title: 'Munkfors-Ransäter församling'},
  {title: 'Nor-Segerstads församling'},
  {title: 'Norra Råda-Sunnemo församling'},
  {title: 'Norrstrands församling'},
  {title: 'Ny församling'},
  {title: 'Ny-Huggenäs församling'},
  {title: 'Rudskoga församling'},
  {title: 'Rännelanda-Lerdal församling'},
  {title: 'Silbodals församling'},
  {title: 'Silleruds församling'},
  {title: 'Skålleruds församling'},
  {title: 'Stavnäs-Högeruds församling'},
  {title: 'Steneby-Tisselskogs församling'},
  {title: 'Stora Kils församling'},
  {title: 'Storfors församling'},
  {title: 'Sundals-Ryrs församling'},
  {title: 'Sunne församling'},
  {title: 'Svanskogs församling'},
  {title: 'Säffle församling'},
  {title: 'Södra Värmlandsnäs församling'},
  {title: 'Torrskogs församling'},
  {title: 'Trankils församling'},
  {title: 'Tveta församling'},
  {title: 'Töcksmarks församling'},
  {title: 'Ulleruds församling'},
  {title: 'Visnums församling'},
  {title: 'Visnums-Kils församling'},
  {title: 'Vitsands församling'},
  {title: 'Värmskogs församling'},
  {title: 'Väse-Fågelviks församling'},
  {title: 'Västerstrands församling'},
  {title: 'Västra Fågelviks församling'},
  {title: 'Västra Ämterviks församling'},
  {title: 'Vårviks församling'},
  {title: 'Älgå församling'},
  {title: 'Ärtemarks församling'},
  {title: 'Åmåls församling'},
  {title: 'Ölme församling'},
  {title: 'Örs församling'},
  {title: 'Östervallskogs församling'},
  {title: 'Östmarks församling'},
  {title: 'Östra Ämterviks församling'},
  {title: 'Övre Älvdals församling'}
]);